openapi: "3.0.0"
info:
  title: Time Server
  version: 1.0.0
paths:
  /api/timeserver/:
    get:
      operationId: getTimev1
      summary: Get current time in UTC and Unix
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples:
                response:
                  value:
                    {
                      "utc": "2020-12-25",
                      "unix": 1608854400
                    }
        '400':
          description: |-
            400 response
          content:
            application/json:
              examples:
                response:
                  value:
                    {
                      "error": "Invalid Date"
                    }
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/timeserver/{dateTime}:
    get:
      summary: Get time for date inputted
      operationId: getTimeWInputv1
      parameters:
        - name: dateTime
          in: path
          required: true
          description: The time in unix or UTC date
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeResponse"
        '400':
          description: Response when input is an invalid date unix or UTC
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  components:
    schemas:
      TimeResponse:
        type: object
        required:
          - utc
          - unix
        properties:
          utc:
            type: string
          unix:
            type: integer
            format: int64
      Error:
        type: object
        required:
          - error
        properties:
          error:
            type: string

